Vagrant.configure("2")  do |config|
    # Create The Common Seting
    config.vm.box = "bento/debian-11"
    config.vm.synced_folder "./shared", "/vagrant_data", create: true

    # Create The Controller Machine
    config.vm.define "foulareS" do |server|
        server.vm.hostname = "foulareS"
        server.vm.network "private_network", ip: "192.168.56.110"
        server.vm.provider "virtualbox" do |vb|
            vb.memory = 1024
            vb.cpus = 1
            vb.name = "foulareS"
        end
        server.vm.provision "shell", path: "k3s-script/controller.sh"
    end

    # Create The Worker Machine
    config.vm.define "foulareSW" do |worker|
        worker.vm.hostname = "foulareSW"
        worker.vm.network "private_network", ip: "192.168.56.111"

        worker.vm.provider "virtualbox" do |vb|
            vb.memory = 512
            vb.cpus = 1
            vb.name = "foulareSW"
        end
        worker.vm.provision "shell", path: "k3s-script/worker.sh"
    end
end